# Generated by Django 4.2.10 on 2025-04-14 00:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('template_content', models.TextField()),
                ('template_fields', models.JSONField()),
                ('category', models.CharField(choices=[('CONTRACT', 'Contract'), ('AGREEMENT', 'Agreement'), ('DECLARATION', 'Declaration'), ('PETITION', 'Petition'), ('POWER_OF_ATTORNEY', 'Power of Attorney'), ('OTHER', 'Other')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'document template',
                'verbose_name_plural': 'document templates',
                'db_table': 'document_templates',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=100)),
                ('document_file', models.FileField(upload_to='generated_documents/')),
                ('field_values', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='document_generation.documenttemplate')),
            ],
            options={
                'verbose_name': 'generated document',
                'verbose_name_plural': 'generated documents',
                'db_table': 'generated_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
