version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
      - ATTORNEY_SERVICE_URL=http://attorney-service:8002
      - CLIENT_SERVICE_URL=http://client-service:8003
      - DOCUMENT_SERVICE_URL=http://document-service:8004
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    networks:
      - backend-network
    depends_on:
      - auth-service
      - attorney-service
      - client-service
      - document-service

  auth-service:
    build:
      context: ./auth-service
    environment:
      - DJANGO_SETTINGS_MODULE=auth_service.settings
      - SECRET_KEY=auth_service_secret_key
      - DEBUG=true
      - ALLOWED_HOSTS=localhost,127.0.0.1,auth-service
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/auth_db
    networks:
      - backend-network
    depends_on:
      - db
    volumes:
      - auth-static:/app/staticfiles
    ports:
      - "8001:8000"

  attorney-service:
    build:
      context: ./attorney-service
    environment:
      - DJANGO_SETTINGS_MODULE=attorney_service.settings
      - SECRET_KEY=attorney_service_secret_key
      - DEBUG=true
      - ALLOWED_HOSTS=localhost,127.0.0.1,attorney-service
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/attorney_db
      - AUTH_SERVICE_URL=http://auth-service:8000/api
    networks:
      - backend-network
    depends_on:
      - db
      - auth-service
    volumes:
      - attorney-static:/app/staticfiles
    ports:
      - "8002:8000"

  client-service:
    build:
      context: ./client-service
    environment:
      - DJANGO_SETTINGS_MODULE=client_service.settings
      - SECRET_KEY=client_service_secret_key
      - DEBUG=true
      - ALLOWED_HOSTS=localhost,127.0.0.1,client-service
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/client_db
      - AUTH_SERVICE_URL=http://auth-service:8000/api
      - ATTORNEY_SERVICE_URL=http://attorney-service:8000/api
    networks:
      - backend-network
    depends_on:
      - db
      - auth-service
      - attorney-service
    volumes:
      - client-static:/app/staticfiles
    ports:
      - "8003:8000"

  document-service:
    build:
      context: ./document-service
    environment:
      - DJANGO_SETTINGS_MODULE=document_service.settings
      - SECRET_KEY=document_service_secret_key
      - DEBUG=true
      - ALLOWED_HOSTS=localhost,127.0.0.1,document-service
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/document_db
      - AUTH_SERVICE_URL=http://auth-service:8000/api
      - CLIENT_SERVICE_URL=http://client-service:8000/api
    networks:
      - backend-network
    depends_on:
      - db
      - auth-service
      - client-service
    volumes:
      - document-static:/app/staticfiles
      - document-media:/app/media
    ports:
      - "8004:8000"

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=auth_db,attorney_db,client_db,document_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh:ro
    networks:
      - backend-network
    ports:
      - "5432:5432"

networks:
  backend-network:
    driver: bridge

volumes:
  postgres-data:
  auth-static:
  attorney-static:
  client-static:
  document-static:
  document-media: 