version: '3.8'

services:
  web:
    build: .
    image: ${DOCKER_IMAGE_NAME:-kinnito/smart-legal-assistance:latest}
    restart: always
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000}
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@legalassistance.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-Admin@123}
      - DJANGO_SETTINGS_MODULE=config.settings.production
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-legal_assistance}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
  media_volume:
  static_volume: 