import type { Metadata } from "next";

import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Script
        src="https://assets.calendly.com/assets/external/widget.js"
        strategy="afterInteractive"
      /> */}
      <body className="antialiased">{children}</body>
    </html>
  );
}
