# Generated by Django 4.2.10 on 2025-04-14 00:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked'), ('PENDING', 'Pending Verification')], default='PENDING', max_length=20)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_pro_bono', models.BooleanField(default=False)),
                ('ratings_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('ratings_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'attorney',
                'verbose_name_plural': 'attorneys',
                'db_table': 'attorneys',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'specialty',
                'verbose_name_plural': 'specialties',
                'db_table': 'attorney_specialties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='attorneys.attorney')),
            ],
            options={
                'verbose_name': 'availability slot',
                'verbose_name_plural': 'availability slots',
                'db_table': 'attorney_availability_slots',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AttorneyCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='attorney_credentials/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='attorneys.attorney')),
            ],
            options={
                'verbose_name': 'attorney credential',
                'verbose_name_plural': 'attorney credentials',
                'db_table': 'attorney_credentials',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
