# Generated by Django 4.2.10 on 2025-04-14 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attorneys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attorneycredential',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attorney',
            name='specialties',
            field=models.ManyToManyField(related_name='attorneys', to='attorneys.specialty'),
        ),
        migrations.AddField(
            model_name='attorney',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attorney_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
