# Generated by Django 5.2 on 2025-05-07 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='attorneyprofile',
            name='degree_document',
            field=models.FileField(blank=True, null=True, upload_to='probono_documents/'),
        ),
        migrations.AddField(
            model_name='attorneyprofile',
            name='expertise',
            field=models.CharField(blank=True, choices=[('criminal', 'Criminal Law'), ('family', 'Family Law'), ('corporate', 'Corporate Law'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='attorneyprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attorneyprofile',
            name='is_pro_bono_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attorneyprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='probono_documents/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='ClientProBonoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='probono_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
