# Generated by Django 4.2.10 on 2025-04-14 00:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('HELPFUL', 'Helpful'), ('SOMEWHAT_HELPFUL', 'Somewhat Helpful'), ('NOT_HELPFUL', 'Not Helpful')], max_length=16)),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'chat feedback',
                'verbose_name_plural': 'chat feedback',
                'db_table': 'chat_feedback',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('USER', 'User Message'), ('BOT', 'Bot Message')], max_length=4)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'chat message',
                'verbose_name_plural': 'chat messages',
                'db_table': 'chat_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'chat session',
                'verbose_name_plural': 'chat sessions',
                'db_table': 'chat_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('resource_type', models.CharField(choices=[('ARTICLE', 'Article'), ('FAQ', 'Frequently Asked Question'), ('DEFINITION', 'Legal Definition'), ('PROCEDURE', 'Legal Procedure'), ('LAW', 'Law Reference')], max_length=10)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'legal resource',
                'verbose_name_plural': 'legal resources',
                'db_table': 'legal_resources',
                'ordering': ['-updated_at'],
            },
        ),
    ]
